### ISSUE TITLE
Using version `@v3` should always point to latest 3.x version

### ISSUE THREAD

**Issue by ddanier** [hustcer/setup-nu#103]
I have been using `hustcer/setup-nu@v3` in https://github.com/ddanier/nur to setup nu inside the GitHub actions. All other dependencies I use update the `@vX` version to the latest X.* version, once a new version is released. Using `@v3` should by this logic currently be the same as `@v3.10`.

Sadly this package does not update the shorter version tags. Thus `@v3` points to a pretty old version, not supporting MacOS builds. This leads to strange errors and is not matching what others are doing.

My suggestion would be to also update major release tags like the `@v3` tag on every new release.

For reference other actions I am using:
* https://github.com/actions/checkout/tags -> `@v4` is currently the same commit SHA1 as `@v4.1.4`
* https://github.com/softprops/action-gh-release/tags -> `@2` is currently the same commit SHA1 as `@v2.0.4`
* https://github.com/actions-rust-lang/setup-rust-toolchain/tags -> `@v1` is currently the same commit SHA1 as `@v1.8.0`, also there is `@v1.8` also pointing to this version

**Comment by hustcer** [comment]
Thanks for the feedback, I have just update v3 tag.

> v3 should always point to latest 3.x version 

I will update the release script later to make sure it's always true

**Comment by ddanier** [comment]
Thanks for the quick reply and instant fix! 👍

**Comment by ddanier** [comment]
I just confirmed this works now using only `@v3`. Thanks again!
