### ISSUE TITLE
enable-plugins as list of relevant plugins

### ISSUE THREAD

**Issue by ttnesby** [hustcer/setup-nu#104]
Hi,

it would be nice to have enable-plugins as a list of relevant plugins to register. E.g.  

enable-plugins: [nu_plugin_polars]

Default empty (nothing to register), otherwise iterate the list, verify availability of plugin and do `plugin add` for existing. Non-existing can be reported.

**Comment by hustcer** [comment]
Should be closed by https://github.com/hustcer/setup-nu/pull/106

**Comment by hustcer** [comment]
enable-plugins could be set to a comma-separated string of plugin names like `nu_plugin_polars,nu_plugin_query`

**Comment by hustcer** [comment]
Ok, maybe I should reopen this issue, the plugins are registered but don't show up in `version`, I'll look into it later!

**Comment by hustcer** [comment]
@ttnesby Confirm fixed in v3.12.
