### ISSUE TITLE
feat: add support for `aarch64_linux` and `aarch64_windows` runners

### ISSUE THREAD

**Issue by maximousblk** [hustcer/setup-nu#108]
I have a project that utilizes self-hosted `aarch64_linux` and `aarch64_windows` GitHub Actions runners. These runners are essential for running Nu scripts to build the application. However, the current GitHub Actions setup does not support these platforms, even though NuShell supports them.

**Comment by hustcer** [comment]
How can I test these two runners?

**Comment by hustcer** [comment]
Try use `uses: hustcer/setup-nu@develop` instead, and tell me if it works
