### ISSUE TITLE
[feat] Use authenticated request

### ISSUE THREAD

**Issue by melMass** [hustcer/setup-nu#67]
Hi @hustcer 

Thanks for this action.
I did not look into the code yet but we are being rate limited (for now we don't cache nu install we will but there is still tests running on nightly that we won't cache).
The solution would be to do authenticated requests. In gh actions it's usually all setup when you run `gh` commands for instance to avoid this.

<img width="1042" alt="API rate limit exceeded for 13.105.117.66. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)" src="https://github.com/hustcer/setup-nu/assets/7041726/53a6d540-cc78-4631-bd50-9bbf09373d56">

**Comment by hustcer** [comment]
Thanks for the Feedback did you add 
'''Yaml

  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
'''
In setup-nu step?

**Comment by melMass** [comment]
> did you add
> 
> ```yaml
>   env:
>     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> In setup-nu step?

Ohhh thanks, I did not!! Makes sense that actions can't access secrets directly, is this a case automatically handled by gh actions in general (passing GITHUB_TOKEN in env for external actions) or did you added it?

**Comment by melMass** [comment]
Thanks It seems to have worked! 
I'll recomment/reopen it if it did not, I'll also read more on the implications of having the token in env 😀

**Comment by hustcer** [comment]
Interesting，I will give it A try later

**Comment by hustcer** [comment]
> @hustcer I think you might be able to use a default one by using `github.token` instead of `secrets`: https://github.com/ad-m/github-push-action/blob/d91a481090679876dfc4178fef17f286781251df/action.yml#L11

It's supported now in v3.9: https://github.com/hustcer/setup-nu/releases/tag/v3.9 
Thanks for the suggestion!
